name: Run Consumer.py on Main Branch

on:
  push:
    branches:
      - main

jobs:
  run-consumer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Consumer.py
        run: python Consumer.py
